import {
  PerpetualMarketSummary,
  PositionUniqueId,
  SubaccountPosition,
} from '@/bonsai/types/summaryTypes';
import { BigNumber } from 'bignumber.js';

import { IndexerPositionSide } from '@/types/indexer/indexerApiGen';

// Mock market summaries
export const mockMarketSummaries: Record<string, PerpetualMarketSummary> = {
  'BTC-USD': {
    assetId: 'BTC',
    displayableAsset: 'Bitcoin',
    displayableTicker: 'BTC-USD',
    ticker: 'BTC-USD',
    marketId: 'BTC-USD',
    clobPairId: 1,
    status: 'ACTIVE',
    baseAsset: 'BTC',
    quoteAsset: 'USDC',
    stepSizeDecimals: 8,
    tickSizeDecimals: 2,
    minOrderSize: '0.001',
    effectiveInitialMarginFraction: 0.05,
    openInterestUSDC: 50000000,
    percentChange24h: 2.5,
    name: 'Bitcoin',
    logo: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png',
    marketCap: 1200000000000,
    volume24h: 25000000000,
    reportedMarketCap: 1200000000000,
    sectorTags: ['Layer 1', 'Store of Value'],
    urls: {
      website: 'https://bitcoin.org',
      technicalDoc: 'https://bitcoin.org/bitcoin.pdf',
      cmc: 'https://coinmarketcap.com/currencies/bitcoin/',
    },
    sparkline24h: [45000, 45200, 44800, 45100, 45500, 45300, 45200],
    isNew: false,
    spotVolume24h: 25000000000,
    isFavorite: true,
    isUnlaunched: false,
    oraclePrice: 45200,
  },
  'ETH-USD': {
    assetId: 'ETH',
    displayableAsset: 'Ethereum',
    displayableTicker: 'ETH-USD',
    ticker: 'ETH-USD',
    marketId: 'ETH-USD',
    clobPairId: 2,
    status: 'ACTIVE',
    baseAsset: 'ETH',
    quoteAsset: 'USDC',
    stepSizeDecimals: 6,
    tickSizeDecimals: 2,
    minOrderSize: '0.01',
    effectiveInitialMarginFraction: 0.05,
    openInterestUSDC: 30000000,
    percentChange24h: -1.2,
    name: 'Ethereum',
    logo: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png',
    marketCap: 400000000000,
    volume24h: 15000000000,
    reportedMarketCap: 400000000000,
    sectorTags: ['Smart Contract Platform', 'DeFi'],
    urls: {
      website: 'https://ethereum.org',
      technicalDoc: 'https://ethereum.org/en/whitepaper/',
      cmc: 'https://coinmarketcap.com/currencies/ethereum/',
    },
    sparkline24h: [3200, 3180, 3220, 3190, 3150, 3170, 3180],
    isNew: false,
    spotVolume24h: 15000000000,
    isFavorite: true,
    isUnlaunched: false,
    oraclePrice: 3180,
  },
  'SOL-USD': {
    assetId: 'SOL',
    displayableAsset: 'Solana',
    displayableTicker: 'SOL-USD',
    ticker: 'SOL-USD',
    marketId: 'SOL-USD',
    clobPairId: 3,
    status: 'ACTIVE',
    baseAsset: 'SOL',
    quoteAsset: 'USDC',
    stepSizeDecimals: 4,
    tickSizeDecimals: 3,
    minOrderSize: '0.1',
    effectiveInitialMarginFraction: 0.1,
    openInterestUSDC: 15000000,
    percentChange24h: 5.8,
    name: 'Solana',
    logo: 'https://assets.coingecko.com/coins/images/4128/large/solana.png',
    marketCap: 80000000000,
    volume24h: 3000000000,
    reportedMarketCap: 80000000000,
    sectorTags: ['Layer 1', 'High Performance'],
    urls: {
      website: 'https://solana.com',
      technicalDoc: 'https://docs.solana.com/',
      cmc: 'https://coinmarketcap.com/currencies/solana/',
    },
    sparkline24h: [180, 185, 182, 188, 192, 190, 188],
    isNew: false,
    spotVolume24h: 3000000000,
    isFavorite: false,
    isUnlaunched: false,
    oraclePrice: 188,
  },
};

// Mock positions data
export const mockPositions: SubaccountPosition[] = [
  {
    // BTC Long Position
    subaccountNumber: 0,
    market: 'BTC-USD',
    side: IndexerPositionSide.LONG,
    size: new BigNumber('0.5'),
    maxSize: new BigNumber('1.0'),
    entryPrice: new BigNumber('44000'),
    realizedPnl: new BigNumber('500'),
    createdAtHeight: new BigNumber('12345678'),
    sumOpen: new BigNumber('22000'),
    sumClose: new BigNumber('0'),
    netFunding: new BigNumber('-25.5'),
    unrealizedPnl: new BigNumber('600'),
    exitPrice: new BigNumber('45200'),
    uniqueId: 'BTC-USD-0' as PositionUniqueId,
    assetId: 'BTC',
    marginMode: 'ISOLATED',
    signedSize: new BigNumber('0.5'),
    unsignedSize: new BigNumber('0.5'),
    notional: new BigNumber('22600'),
    value: new BigNumber('22600'),
    adjustedImf: new BigNumber('0.05'),
    adjustedMmf: new BigNumber('0.03'),
    initialRisk: new BigNumber('1130'),
    maintenanceRisk: new BigNumber('678'),
    maxLeverage: new BigNumber('20'),
    baseEntryPrice: new BigNumber('44000'),
    baseNetFunding: new BigNumber('-25.5'),
    leverage: new BigNumber('20'),
    marginValueInitial: new BigNumber('1130'),
    marginValueMaintenance: new BigNumber('678'),
    updatedUnrealizedPnl: new BigNumber('600'),
    updatedUnrealizedPnlPercent: new BigNumber('5.31'),
    liquidationPrice: new BigNumber('42000'),
  },
  {
    // ETH Short Position
    subaccountNumber: 0,
    market: 'ETH-USD',
    side: IndexerPositionSide.SHORT,
    size: new BigNumber('2.0'),
    maxSize: new BigNumber('5.0'),
    entryPrice: new BigNumber('3250'),
    realizedPnl: new BigNumber('-100'),
    createdAtHeight: new BigNumber('12345679'),
    sumOpen: new BigNumber('6500'),
    sumClose: new BigNumber('0'),
    netFunding: new BigNumber('15.2'),
    unrealizedPnl: new BigNumber('-140'),
    exitPrice: new BigNumber('3180'),
    uniqueId: 'ETH-USD-0' as PositionUniqueId,
    assetId: 'ETH',
    marginMode: 'CROSS',
    signedSize: new BigNumber('-2.0'),
    unsignedSize: new BigNumber('2.0'),
    notional: new BigNumber('6360'),
    value: new BigNumber('-6360'),
    adjustedImf: new BigNumber('0.05'),
    adjustedMmf: new BigNumber('0.03'),
    initialRisk: new BigNumber('318'),
    maintenanceRisk: new BigNumber('190.8'),
    maxLeverage: new BigNumber('20'),
    baseEntryPrice: new BigNumber('3250'),
    baseNetFunding: new BigNumber('15.2'),
    leverage: new BigNumber('20'),
    marginValueInitial: new BigNumber('318'),
    marginValueMaintenance: new BigNumber('190.8'),
    updatedUnrealizedPnl: new BigNumber('-140'),
    updatedUnrealizedPnlPercent: new BigNumber('-2.15'),
    liquidationPrice: new BigNumber('3400'),
  },
  {
    // SOL Long Position
    subaccountNumber: 0,
    market: 'SOL-USD',
    side: IndexerPositionSide.LONG,
    size: new BigNumber('50'),
    maxSize: new BigNumber('100'),
    entryPrice: new BigNumber('175'),
    realizedPnl: new BigNumber('0'),
    createdAtHeight: new BigNumber('12345680'),
    sumOpen: new BigNumber('8750'),
    sumClose: new BigNumber('0'),
    netFunding: new BigNumber('-5.5'),
    unrealizedPnl: new BigNumber('650'),
    exitPrice: new BigNumber('188'),
    uniqueId: 'SOL-USD-0' as PositionUniqueId,
    assetId: 'SOL',
    marginMode: 'ISOLATED',
    signedSize: new BigNumber('50'),
    unsignedSize: new BigNumber('50'),
    notional: new BigNumber('9400'),
    value: new BigNumber('9400'),
    adjustedImf: new BigNumber('0.1'),
    adjustedMmf: new BigNumber('0.05'),
    initialRisk: new BigNumber('940'),
    maintenanceRisk: new BigNumber('470'),
    maxLeverage: new BigNumber('10'),
    baseEntryPrice: new BigNumber('175'),
    baseNetFunding: new BigNumber('-5.5'),
    leverage: new BigNumber('10'),
    marginValueInitial: new BigNumber('940'),
    marginValueMaintenance: new BigNumber('470'),
    updatedUnrealizedPnl: new BigNumber('650'),
    updatedUnrealizedPnlPercent: new BigNumber('7.43'),
    liquidationPrice: new BigNumber('160'),
  },
];

// Mock orders data (empty for now, but structure is ready)
export const mockOrders = {
  stopLossOrders: [],
  takeProfitOrders: [],
};
