/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.103.0
*/

export { IncreasePositionScript } from "./IncreasePositionScript.js";
export { DecreasePositionScript } from "./DecreasePositionScript.js";
